# ──────────────────────────────────────────────
#  _config.yml  – GitHub Pages site settings
# ──────────────────────────────────────────────

title: ""                                # disable auto-inserted H1
description: "Portfolio of Milad Ketabi – ML & AI Engineering"
theme: minima                             # or any other GitHub-hosted theme

# Minima-specific toggle that hides the theme’s page title header
show_title: false

# Optional: use GitHub-flavoured Markdown everywhere
markdown: kramdown
kramdown:
  input: GFM

# Optional: default plugins that GitHub Pages supports
plugins:
  - jekyll-feed
  - jekyll-seo-tag
