title: "Milad Ketabi"
description: "Portfolio of Milad Ketabi – ML & AI Engineering"
theme: jekyll-theme-modernist

markdown: kramdown
kramdown:
  input: GFM

plugins:
  - jekyll-feed
  - jekyll-seo-tag
